import type { Game, City, Branch, Review, LeaderboardEntry, SiteStats, TimeSlot } from '@/types'

export const MOCK_CITIES: City[] = [
  { id: '1', name: 'تهران', slug: 'tehran', province: 'تهران' },
  { id: '2', name: 'کرج', slug: 'karaj', province: 'البرز' },
  { id: '3', name: 'اصفهان', slug: 'isfahan', province: 'اصفهان' },
  { id: '4', name: 'مشهد', slug: 'mashhad', province: 'خراسان رضوی' },
  { id: '5', name: 'شیراز', slug: 'shiraz', province: 'فارس' },
]

export const MOCK_BRANCHES: Branch[] = [
  {
    id: '1',
    name: 'شعبه ونک',
    address: 'تهران، ونک، خیابان ملاصدرا',
    city: MOCK_CITIES[0],
    lat: 35.7448,
    lng: 51.4113,
    phone: '02188880001',
    instagram: 'tiktakrun',
  },
  {
    id: '2',
    name: 'شعبه کرج',
    address: 'کرج، میدان توحید، بلوار شهید بهشتی',
    city: MOCK_CITIES[1],
    lat: 35.8361,
    lng: 50.9984,
    phone: '02632220002',
    instagram: 'tiktakrun',
  },
  {
    id: '3',
    name: 'شعبه جردن',
    address: 'تهران، جردن، خیابان آفریقا',
    city: MOCK_CITIES[0],
    lat: 35.7611,
    lng: 51.4127,
    phone: '02188880003',
    instagram: 'tiktakrun',
  },
]

export const MOCK_GAMES: Game[] = [
  {
    id: '1',
    title: 'دخمه ملعون',
    slug: 'dokhme-maloun',
    subtitle: 'آیا می‌توانید از دخمه نجات یابید؟',
    description: 'در اعماق یک دخمه قدیمی، افسانه‌ای ترسناک زندگی می‌کند. شما ۶۰ دقیقه فرصت دارید تا معمای شوم را حل کنید و پیش از آنکه در قفل شود، فرار کنید.',
    scenario: 'سال‌هاست که این دخمه متروک مانده. آنچه در اینجا اتفاق افتاده هرگز گفته نشده. شما تیمی از ماجراجویان هستید که باید حقیقت را کشف کنید...',
    category: 'ESCAPE_ROOM',
    genre: 'HORROR',
    difficulty: 'HARD',
    fearLevel: 4,
    minPlayers: 2,
    maxPlayers: 6,
    duration: 60,
    basePrice: 890000,
    pricePerPlayer: 150000,
    coverImage: 'https://picsum.photos/seed/dungeon/800/500',
    images: [
      { id: '1', url: 'https://picsum.photos/seed/dungeon1/800/500', alt: 'دخمه ملعون', isPrimary: true },
      { id: '2', url: 'https://picsum.photos/seed/dungeon2/800/500', alt: 'اتاق اصلی', isPrimary: false },
      { id: '3', url: 'https://picsum.photos/seed/dungeon3/800/500', alt: 'معما', isPrimary: false },
    ],
    branch: MOCK_BRANCHES[0],
    rating: 4.8,
    totalReviews: 234,
    successRate: 23,
    isActive: true,
    hasAgeLimit: true,
    ageLimit: 14,
    warningText: 'مناسب افراد مبتلا به بیماری قلبی نیست',
    sections: ['featured', 'tehran'],
    tags: ['ترسناک', 'معمایی', 'اتاق فرار', 'شبانه'],
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'بیمارستان شب',
    slug: 'bimarestan-shab',
    subtitle: 'بازگشت به کابوس',
    description: 'بیمارستانی که سال‌هاست متروک مانده. صداهای عجیب از راهروها می‌آید. آیا می‌توانید حقیقت پشت درهای بسته را کشف کنید؟',
    scenario: 'این بیمارستان ۲۰ سال پیش بسته شد. اما چرا؟ پرونده‌های مفقوده، بیماران ناپدیدشده، پزشکانی که دیوانه شدند...',
    category: 'ESCAPE_ROOM',
    genre: 'HORROR',
    difficulty: 'EXPERT',
    fearLevel: 5,
    minPlayers: 3,
    maxPlayers: 8,
    duration: 75,
    basePrice: 1200000,
    pricePerPlayer: 180000,
    coverImage: 'https://picsum.photos/seed/hospital/800/500',
    images: [
      { id: '4', url: 'https://picsum.photos/seed/hospital1/800/500', alt: 'بیمارستان', isPrimary: true },
      { id: '5', url: 'https://picsum.photos/seed/hospital2/800/500', alt: 'اتاق عمل', isPrimary: false },
    ],
    branch: MOCK_BRANCHES[2],
    rating: 4.9,
    totalReviews: 456,
    successRate: 12,
    isActive: true,
    hasAgeLimit: true,
    ageLimit: 16,
    warningText: 'برای افراد با مشکل قلبی، بارداران و افراد مبتلا به فوبیا توصیه نمی‌شود',
    sections: ['featured', 'weekly-discount', 'tehran'],
    tags: ['ترسناک', 'اتاق فرار', 'تاریک'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '3',
    title: 'سینما ترس',
    slug: 'cinema-tars',
    subtitle: 'تجربه‌ای که باور نخواهید کرد',
    description: 'یک تجربه سینمایی کاملاً غوطه‌ور! بازیگران واقعی، داستان ترسناک، و شما در قلب ماجرا.',
    scenario: 'شما وارد یک نمایش زنده می‌شوید که خط بین واقعیت و خیال را محو می‌کند.',
    category: 'CINEMA_HORROR',
    genre: 'HORROR',
    difficulty: 'MEDIUM',
    fearLevel: 4,
    minPlayers: 1,
    maxPlayers: 20,
    duration: 90,
    basePrice: 450000,
    pricePerPlayer: 450000,
    coverImage: 'https://picsum.photos/seed/cinema/800/500',
    images: [
      { id: '6', url: 'https://picsum.photos/seed/cinema1/800/500', alt: 'سینما ترس', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[0],
    rating: 4.6,
    totalReviews: 123,
    successRate: 100,
    isActive: true,
    hasAgeLimit: true,
    ageLimit: 15,
    warningText: 'برای بارداران توصیه نمی‌شود',
    sections: ['cinema-horror', 'featured'],
    tags: ['سینما', 'ترسناک', 'تجربی'],
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '4',
    title: 'بازی تخت',
    slug: 'bazi-takht',
    subtitle: 'استراتژی، هوش و رقابت',
    description: 'بهترین انتخاب برای دوستانی که عاشق بازی‌های رومیزی هستند. ۱۰۰+ بازی برتر دنیا منتظر شما.',
    scenario: 'در این سالن هوشمند، با دوستانتان به رقابت بپردازید.',
    category: 'BOARD_GAME',
    genre: 'MYSTERY',
    difficulty: 'EASY',
    fearLevel: 0,
    minPlayers: 2,
    maxPlayers: 10,
    duration: 120,
    basePrice: 250000,
    pricePerPlayer: 80000,
    coverImage: 'https://picsum.photos/seed/boardgame/800/500',
    images: [
      { id: '7', url: 'https://picsum.photos/seed/boardgame1/800/500', alt: 'بازی رومیزی', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[0],
    rating: 4.5,
    totalReviews: 89,
    successRate: 100,
    isActive: true,
    hasAgeLimit: false,
    sections: ['board-games'],
    tags: ['رومیزی', 'خانوادگی', 'استراتژی'],
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: '5',
    title: 'لیزرتگ نبرد',
    slug: 'lasertag-nabard',
    subtitle: 'نبرد در تاریکی',
    description: 'آماده جنگ الکترونیکی باشید! در آرنای لیزرتگ ما، تیم‌ها با یکدیگر رقابت می‌کنند.',
    scenario: 'دو تیم، یک هدف، صفر رحم. برنده باش یا از بین برو.',
    category: 'LASER_TAG',
    genre: 'ACTION',
    difficulty: 'MEDIUM',
    fearLevel: 1,
    minPlayers: 4,
    maxPlayers: 16,
    duration: 45,
    basePrice: 300000,
    pricePerPlayer: 120000,
    coverImage: 'https://picsum.photos/seed/laser/800/500',
    images: [
      { id: '8', url: 'https://picsum.photos/seed/laser1/800/500', alt: 'لیزرتگ', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[1],
    rating: 4.7,
    totalReviews: 178,
    successRate: 100,
    isActive: true,
    hasAgeLimit: false,
    sections: ['laser-tag', 'karaj'],
    tags: ['لیزر', 'اکشن', 'گروهی'],
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: '6',
    title: 'واقعیت مجازی',
    slug: 'vr-experience',
    subtitle: 'ورود به دنیای دیگر',
    description: 'با هدست‌های پیشرفته VR وارد دنیاهای خیالی شوید. تجربه‌ای که واقعی‌تر از واقعیت است.',
    scenario: 'انتخاب کنید: جنگل ترسناک، فضا، اعماق اقیانوس یا دنیای آخرالزمانی.',
    category: 'VR',
    genre: 'SCI_FI',
    difficulty: 'EASY',
    fearLevel: 2,
    minPlayers: 1,
    maxPlayers: 4,
    duration: 30,
    basePrice: 350000,
    pricePerPlayer: 350000,
    coverImage: 'https://picsum.photos/seed/vr/800/500',
    images: [
      { id: '9', url: 'https://picsum.photos/seed/vr1/800/500', alt: 'واقعیت مجازی', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[0],
    rating: 4.4,
    totalReviews: 201,
    successRate: 100,
    isActive: true,
    hasAgeLimit: false,
    sections: ['vr'],
    tags: ['VR', 'مجازی', 'فناوری'],
    createdAt: '2024-03-15T00:00:00Z',
  },
  {
    id: '7',
    title: 'پینت‌بال ارتشی',
    slug: 'paintball-arteshi',
    subtitle: 'رزم واقعی با رنگ',
    description: 'در زمین پینت‌بال ما، یک نبرد واقعی تجربه کنید. تجهیزات حرفه‌ای، زمین وسیع.',
    scenario: 'دو تیم، هدف گرفتن پرچم دشمن. آیا استراتژی‌تان کافی است؟',
    category: 'PAINTBALL',
    genre: 'ACTION',
    difficulty: 'MEDIUM',
    fearLevel: 1,
    minPlayers: 6,
    maxPlayers: 20,
    duration: 60,
    basePrice: 800000,
    pricePerPlayer: 130000,
    coverImage: 'https://picsum.photos/seed/paintball/800/500',
    images: [
      { id: '10', url: 'https://picsum.photos/seed/paintball1/800/500', alt: 'پینت بال', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[1],
    rating: 4.6,
    totalReviews: 145,
    successRate: 100,
    isActive: true,
    hasAgeLimit: false,
    sections: ['paintball', 'karaj'],
    tags: ['پینت‌بال', 'اکشن', 'گروهی', 'هوای آزاد'],
    createdAt: '2024-04-01T00:00:00Z',
  },
  {
    id: '8',
    title: 'قلعه شیطان',
    slug: 'ghale-sheitan',
    subtitle: 'دژ تاریک اسرار',
    description: 'در دژ قرون وسطایی ما، یک سری معما و تله در انتظار شماست. آیا می‌توانید قلعه را فتح کنید؟',
    scenario: 'در قرن ۱۵، ارباب این قلعه جادوگری کرد و روح شر را صدا زد...',
    category: 'ESCAPE_ROOM',
    genre: 'FANTASY',
    difficulty: 'HARD',
    fearLevel: 3,
    minPlayers: 2,
    maxPlayers: 7,
    duration: 70,
    basePrice: 950000,
    pricePerPlayer: 160000,
    coverImage: 'https://picsum.photos/seed/castle/800/500',
    images: [
      { id: '11', url: 'https://picsum.photos/seed/castle1/800/500', alt: 'قلعه', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[2],
    rating: 4.7,
    totalReviews: 312,
    successRate: 18,
    isActive: true,
    hasAgeLimit: true,
    ageLimit: 12,
    sections: ['featured', 'weekly-discount', 'tehran'],
    tags: ['قرون وسطا', 'فانتزی', 'معما'],
    createdAt: '2024-04-15T00:00:00Z',
  },
  {
    id: '9',
    title: 'زیردریایی گمشده',
    slug: 'zirdaryaee-gomshodeh',
    subtitle: 'در اعماق اقیانوس',
    description: 'زیردریایی شما خراب شده و در اعماق آب گرفتار شده‌اید. ۶۰ دقیقه برای نجات فرصت دارید.',
    scenario: 'بخش‌های مختلف زیردریایی آسیب دیده. هر گروه باید بخش خود را تعمیر کند...',
    category: 'ESCAPE_ROOM',
    genre: 'SCI_FI',
    difficulty: 'MEDIUM',
    fearLevel: 2,
    minPlayers: 3,
    maxPlayers: 9,
    duration: 60,
    basePrice: 750000,
    pricePerPlayer: 140000,
    coverImage: 'https://picsum.photos/seed/submarine/800/500',
    images: [
      { id: '12', url: 'https://picsum.photos/seed/submarine1/800/500', alt: 'زیردریایی', isPrimary: true },
    ],
    branch: MOCK_BRANCHES[0],
    rating: 4.5,
    totalReviews: 267,
    successRate: 35,
    isActive: true,
    hasAgeLimit: false,
    sections: ['featured'],
    tags: ['اقیانوس', 'علمی‌تخیلی', 'گروهی'],
    createdAt: '2024-05-01T00:00:00Z',
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    user: { id: 'u1', name: 'علی محمدی', avatar: 'https://picsum.photos/seed/user1/50/50' },
    game: { id: '1', title: 'دخمه ملعون' },
    rating: 5,
    comment: 'باورنکردنی بود! جیغ بچه‌ها خونه رو گذاشت کنار. بهترین اتاق فراری بودم تو عمرم. طراحی خیلی حرفه‌ای و واقعی.',
    helpful: 45,
    createdAt: '2024-05-10T00:00:00Z',
    isVerified: true,
  },
  {
    id: '2',
    user: { id: 'u2', name: 'سارا احمدی', avatar: 'https://picsum.photos/seed/user2/50/50' },
    game: { id: '2', title: 'بیمارستان شب' },
    rating: 5,
    comment: 'من آدم ترسویی نیستم ولی اینجا واقعاً ترسیدم! همه چیز اون قدر واقعی بود که فراموش می‌کنی اتاق فراره.',
    helpful: 38,
    createdAt: '2024-05-15T00:00:00Z',
    isVerified: true,
  },
  {
    id: '3',
    user: { id: 'u3', name: 'رضا کریمی', avatar: 'https://picsum.photos/seed/user3/50/50' },
    game: { id: '8', title: 'قلعه شیطان' },
    rating: 4,
    comment: 'معماها خیلی باهوشانه طراحی شده بودن. دوبار رفتم و هر بار چیز جدیدی کشف کردم!',
    helpful: 22,
    createdAt: '2024-05-20T00:00:00Z',
    isVerified: true,
  },
]

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    user: { id: 'u10', mobile: '09xxxxxx', name: 'مهران ظفری', avatar: 'https://picsum.photos/seed/player1/80/80', walletBalance: 0, xp: 15420, rank: 1, totalBookings: 89, successRate: 95, inviteCode: 'TTR001', createdAt: '' },
    score: 15420,
    gamesPlayed: 89,
    period: 'WEEKLY',
  },
  {
    rank: 2,
    user: { id: 'u11', mobile: '09xxxxxx', name: 'نیلوفر رستمی', avatar: 'https://picsum.photos/seed/player2/80/80', walletBalance: 0, xp: 12890, rank: 2, totalBookings: 67, successRate: 88, inviteCode: 'TTR002', createdAt: '' },
    score: 12890,
    gamesPlayed: 67,
    period: 'WEEKLY',
  },
  {
    rank: 3,
    user: { id: 'u12', mobile: '09xxxxxx', name: 'امیر حسین تهرانی', avatar: 'https://picsum.photos/seed/player3/80/80', walletBalance: 0, xp: 11200, rank: 3, totalBookings: 55, successRate: 82, inviteCode: 'TTR003', createdAt: '' },
    score: 11200,
    gamesPlayed: 55,
    period: 'WEEKLY',
  },
  {
    rank: 4,
    user: { id: 'u13', mobile: '09xxxxxx', name: 'فاطمه مرادی', avatar: 'https://picsum.photos/seed/player4/80/80', walletBalance: 0, xp: 9870, rank: 4, totalBookings: 44, successRate: 79, inviteCode: 'TTR004', createdAt: '' },
    score: 9870,
    gamesPlayed: 44,
    period: 'WEEKLY',
  },
  {
    rank: 5,
    user: { id: 'u14', mobile: '09xxxxxx', name: 'داود حیدری', avatar: 'https://picsum.photos/seed/player5/80/80', walletBalance: 0, xp: 8540, rank: 5, totalBookings: 38, successRate: 76, inviteCode: 'TTR005', createdAt: '' },
    score: 8540,
    gamesPlayed: 38,
    period: 'WEEKLY',
  },
]

export const MOCK_STATS: SiteStats = {
  totalGames: 48,
  totalBookings: 12547,
  successRate: 28,
  minAge: 10,
  maxAge: 65,
  citiesCount: 5,
}

export const MOCK_SLOTS: TimeSlot[] = [
  { id: 's1', startTime: '10:00', endTime: '11:00', availableCapacity: 4, totalCapacity: 6, price: 890000, isAvailable: true },
  { id: 's2', startTime: '12:00', endTime: '13:00', availableCapacity: 0, totalCapacity: 6, price: 890000, isAvailable: false },
  { id: 's3', startTime: '14:00', endTime: '15:00', availableCapacity: 6, totalCapacity: 6, price: 890000, isAvailable: true },
  { id: 's4', startTime: '16:00', endTime: '17:00', availableCapacity: 2, totalCapacity: 6, price: 980000, isAvailable: true },
  { id: 's5', startTime: '18:00', endTime: '19:00', availableCapacity: 1, totalCapacity: 6, price: 980000, isAvailable: true },
  { id: 's6', startTime: '20:00', endTime: '21:00', availableCapacity: 5, totalCapacity: 6, price: 1100000, isAvailable: true },
  { id: 's7', startTime: '22:00', endTime: '23:00', availableCapacity: 6, totalCapacity: 6, price: 1100000, isAvailable: true },
]
